title = "Vale.Rocks"
id = "https://vale.rocks"
# icon = ""
# logo = ""
rights = "© Declan Chidlow"
subtitle = "A collection of unhinged (yet not completely insane) ramblings."
base = "https://vale.rocks"
lang = "en-AU"

[main]

[[main.block]]
format = "html"
content_file = "../global/elements/head.html"

[[main.block]]
format = "html"
content_file = "../global/elements/bloghead.html"

[[main.block]]
format = "style"
content = ":root{--header_background: var(--magenta)}"

[[main.block]]
format = "html"
content = "<body>"

[[main.block]]
format = "html"
content_file = "../global/elements/navbar.html"

[[main.block]]
format = "html"
content = """\
	<div id='scroll-indicator-container'>\
		<div id="scroll-indicator"></div>\
	</div>\
	<script src='/scripts/scroll-indicator.js'></script>\
	<script src='/scripts/figure-modal.js'></script>\
	"""

[[main.block]]
format = "span"
id = "section"
content = "Posts"

[[main.block]]
format = "document"

[[main.block]]
format = "html"
content_file = "../global/elements/footer.html"
