title = "Vale.Rocks"
link = "https://vale.rocks"
description = "A collection of unhinged (yet not completely insane) ramblings."

[main]

[[main.block]]
format = "html"
content_file = "../config/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "../config/global/elements/bloghead.html"

[[main.block]]
format = "html"
content_file = "../config/global/elements/navbar.html"

[[main.block]]
format = "html"
content = "<span id='section'>Posts</span>"

[[main.block]]
format = "html"
content = "<style>:root{--header_background: var(--magenta)}</style>"

[[main.block]]
format = "html"
content = "<div id='fullscreenModal'><span id='close' class='material-icons'>close</span><img id='fullscreenImg'><p id='caption'></p><hr/><p id='altText'></p></div><script src='/scripts/figureview.js'></script>"
