[main]

[[main.block]]
format = "html"
content_file = "../global/elements/head.html"

[[main.block]]
format = "html"
content = "<style>:root{--header_background: var(--green)}</style>"

[[main.block]]
format = "html"
content = "<body>"

[[main.block]]
format = "html"
content_file = "../global/elements/navbar.html"

[[main.block]]
format = "html"
content = "<span id='section'>Portfolio</span><div id='postbody'>"

[[main.block]]
format = "html"
content = "<div id='fullscreenModal'><span id='close' class='material-icons'>close</span><img id='fullscreenImg'><p id='caption'></p><hr/><p id='altText'></p></div><script src='/scripts/figureview.js'></script>"

[[main.block]]
format = "document"

[[main.block]]
format = "html"
content_file = "../global/elements/footer.html"
