[main]

[[main.block]]
format = "html"
content_file = "../global/elements/head.html"

[[main.block]]
format = "html"
content = "<meta property='article:section' content='Portfolio' />"

[[main.block]]
format = "html"
content_file = "../global/elements/article-head.html"

[[main.block]]
format = "style"
content = ":root{--header_background: var(--green)}"

[[main.block]]
format = "html"
content = "</head><body>"

[[main.block]]
format = "html"
content_file = "../global/elements/navbar.html"

[[main.block]]
format = "span"
id = "section"
content = "Portfolio"

[[main.block]]
format = "html"
content = """\
	<div id='scroll-indicator-container'>\
		<div id="scroll-indicator"></div>\
	</div>\
	<script src='/scripts/scroll-indicator.js'></script>\
	"""

[[main.block]]
format = "document"

[[main.block]]
format = "html"
content_file = "../global/elements/footer.html"
