[main]

[[main.block]]
format = "html"
content_file = "../config/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "../config/global/elements/navbar.html"

[[main.block]]
format = "html"
content = "<span id='section'>Portfolio</span><div id='postbody'>"

[[main.block]]
format = "html"
content = "<style>:root{--header_background: var(--green)}</style>"
