title = "Vale.Rocks Portfolio"
link = "https://vale.rocks"
description = "A collection of works and creations by Declan Chidlow."

[main]

[[main.block]]
from_str = "../config/global/elements/head.html"
style = "html"

[[main.block]]
from_str = "../config/global/elements/navbar.html"
style = "html"

[[main.block]]
text = "<span id='section'>Portfolio</span><div id='postbody'>"
style = "html"

[[main.block]]
text = "<style>:root{--header_background: var(--green)}</style>"
style = "html"
