[main]

[[main.block]]
format = "html"
content_file = "config/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "config/pages/posts/head.html"

[[main.block]]
format = "html"
content_file = "config/global/elements/navbar.html"

[[main.block]]
format = "html"
content_file = "config/pages/posts/posts.html"

[[main.block]]
format = "html"
content_file = "config/global/elements/footer.html"
