[main]

[[main.block]]
from_str = "config/global/elements/head.html"
style = "html"

[[main.block]]
from_str = "config/pages/posts/head.html"
style = "html"

[[main.block]]
from_str = "config/global/elements/navbar.html"
style = "html"

[[main.block]]
from_str = "config/pages/posts/posts.html"
style = "html"

[[main.block]]
from_str = "config/global/elements/footer.html"
style = "html"
