[main]

[[main.block]]
format = "html"
content_file = "config/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "config/pages/support/head.html"

[[main.block]]
format = "html"
content_file = "config/global/elements/navbar.html"

[[main.block]]
format = "md"
content_file = "config/pages/support/support.md"

[[main.block]]
format = "html"
content_file = "config/global/elements/footer.html"
