title = "Vale.Rocks"
id = "https://vale.rocks"
# icon = ""
# logo = ""
rights = "© Declan Chidlow"
subtitle = "A collection of unhinged (yet not completely insane) ramblings."
base = "https://vale.rocks"
lang = "en-AU"

[main]

[[main.block]]
format = "html"
content_file = "../config/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "../config/global/elements/bloghead.html"

[[main.block]]
format = "html"
content = "<style>:root{--header_background: var(--magenta)}</style>"

[[main.block]]
format = "html"
content = "<body>"

[[main.block]]
format = "html"
content_file = "../config/global/elements/navbar.html"

[[main.block]]
format = "html"
content = "<span id='section'>Posts</span>"

[[main.block]]
format = "html"
content = "<div id='fullscreenModal'><span id='close' class='material-icons'>close</span><img id='fullscreenImg'><p id='caption'></p><hr/><p id='altText'></p></div><script src='/scripts/figureview.js'></script>"

[[main.block]]
format = "document"

[[main.block]]
format = "html"
content_file = "../config/global/elements/footer.html"
